name: App-deployment
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependicies
        run: npm install
        
      - name: Time out 60sec
        run: |
          timeout 60s npm start || true
          
      - name: Installing docker
        uses: docker/build-push-action@v5
        
      - name: Docker version
        run: docker --version ; chmod 777 /var/lib/docker.sock
        
        
      - name: Build image
        run: docker build -t myimage .
        
      - name: run Container
        run: docker run -itd -p 9000:3000 myimage
      
        
        
