name: App-deployment
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
                
      - name: SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          token: ${{ secrets.SONARQUBE_TOKEN }} 
          args: >
            -Dsonar.projectKey=myproject
            -Dsonar.projectName=myproject
  image: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4 
      - name: Installing docker
        uses: docker/setup-buildx-action@v4
      - name: Docker version
        run: |
          docker --version 
      - name: Build image
        run: docker build -t myimage .
      - name: run Container
        run: docker run -d -p 9000:3000 myimage
   
      
        
        
