---
name: Deployment
on: 
  workflow_dispatch: 
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: code checkout
          uses: actions/checkout@v4 
        - name: Installing docker
          uses: docker/setup-buildx-action@v4
        - name: setup kubectl
          run: |
             curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
             chmod +x ./kind
             sudo mv ./kind /usr/local/bin/kind
             kind version
        - name: install kubectl
          run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
            chmod +x kubectl
            mkdir -p ~/.local/bin
            mv ./kubectl ~/.local/bin/kubectl
            pwd
            ls -lrth
